#ifndef _CustomFunctionMapping
#define _CustomFunctionMapping

//SMP3 COMMAND AND RESPONSE

#define SMP3_CMODE 0x42
#define SMP3_CMODE_REQUEST_DATA_LENGTH 5
#define SMP3_CMODE_RESPONSE_DATA_LENGTH 4

#define SMP3_READ_BUFFER 0x43
#define SMP3_READ_BUFFER_REQUEST_DATA_LENGTH 5
#define SMP3_READ_BUFFER_RESPONSE_DATA_LENGTH 132

#define SMP3_GET_REGISTERS 0x44
#define SMP3_GET_REGISTERS_REQUEST_DATA_LENGTH 7
#define SMP3_GET_REGISTERS_RESPONSE_DATA_LENGTH 80

#define SMP3_SET_REGISTERS 0x45
#define SMP3_SET_REGISTERS_REQUEST_DATA_LENGTH 82
#define SMP3_SET_REGISTERS_RESPONSE_DATA_LENGTH 4

#define SMP3_WRITE_EEPROM 0x65
#define SMP3_WRITE_EEPROM_REQUEST_DATA_LENGTH 4
#define SMP3_WRITE_EEPROM_RESPONSE_DATA_LENGTH 4

#define SMP3_SET_SPEED 0x6A
#define SMP3_SET_SPEED_REQUEST_DATA_LENGTH 5
#define SMP3_SET_SPEED_RESPONSE_DATA_LENGTH 4

#define SMP3_SEND_ID 0x6B
#define SMP3_SEND_ID_REQUEST_DATA_LENGTH 4
#define SMP3_SEND_ID_RESPONSE_DATA_LENGTH 17

#define ERROR_FUNCTION 0x80
#define ERROR_FUNCTION_REQUEST_DATA_LENGTH 5
#define ERROR_FUNCTION_RESPONSE_DATA_LENGTH 0

// DataFransfer, ScanController, RemoteAccess

#define SCANCONTROLLER_FUNCTION      0x50
#define SCANCONTROLLER_FUNCTION_REQUEST_DATA_LENGTH      4
#define SCANCONTROLLER_FUNCTION_RESPONSE_DATA_LENGTH      5

#define REGISTERCONTROLLER_FUNCTION      0x51
#define REGISTERCONTROLLER_FUNCTION_REQUEST_DATA_LENGTH      5
#define REGISTERCONTROLLER_FUNCTION_RESPONSE_DATA_LENGTH      4

#define DEVICEWASHALTED_FUNCTION      0x52
#define DEVICEWASHALTED_FUNCTION_REQUEST_DATA_LENGTH      4
#define DEVICEWASHALTED_FUNCTION_RESPONSE_DATA_LENGTH      4

#define REQUESTDATA_FUNCTION      0x53
#define REQUESTDATA_FUNCTION_REQUEST_DATA_LENGTH      14
#define REQUESTDATA_FUNCTION_RESPONSE_DATA_LENGTH      6
#define BEGINDATASEND_FUNCTION_RESPONSE_DATA_LENGTH      4

#define SENDDATAPACKET_FUNCTION      0x54
#define SENDDATAPACKET_FUNCTION_REQUEST_DATA_LENGTH      255
#define SENDDATAPACKET_FUNCTION_RESPONSE_DATA_LENGTH      4

#define DATAPACKETRECEIVED_FUNCTION      0x54
#define DATAPACKETRECEIVED_FUNCTION_REQUEST_DATA_LENGTH      5
#define DATAPACKETRECEIVED_FUNCTION_RESPONSE_DATA_LENGTH      4

#define DATATRANSACTIONCOMPLITED_FUNCTION      0x55
#define DATATRANSACTIONCOMPLITED_FUNCTION_REQUEST_DATA_LENGTH      4
#define DATATRANSACTIONCOMPLITED_FUNCTION_RESPONSE_DATA_LENGTH      4
#define ENDDATASEND_FUNCTION_RESPONSE_DATA_LENGTH      4

#define BEGINREMOTECONTROL_FUNCTION      0x56
#define BEGINREMOTECONTROL_FUNCTION_REQUEST_DATA_LENGTH      4
#define BEGINREMOTECONTROL_FUNCTION_RESPONSE_DATA_LENGTH      4

#define SENDDEVICEFILES_FUNCTION      0x57
#define SENDDEVICEFILES_FUNCTION_REQUEST_DATA_LENGTH      8
#define SENDDEVICEFILES_FUNCTION_RESPONSE_DATA_LENGTH      4

#define REQUESTDEVICEFILE_FUNCTION      0x58
#define REQUESTDEVICEFILE_FUNCTION_REQUEST_DATA_LENGTH      8
#define REQUESTDEVICEFILE_FUNCTION_RESPONSE_DATA_LENGTH      4

#define SAVEDEVICEFILES_FUNCTION      0x59
#define SAVEDEVICEFILES_FUNCTION_REQUEST_DATA_LENGTH      8
#define SAVEDEVICEFILES_FUNCTION_RESPONSE_DATA_LENGTH      4

#define DEVICEFILEUPLOAD_FUNCTION      0x5A
#define DEVICEFILEUPLOAD_FUNCTION_REQUEST_DATA_LENGTH      8
#define DEVICEFILEUPLOAD_FUNCTION_RESPONSE_DATA_LENGTH      4

#define COMPLITEREMOTECONTROL_FUNCTION      0x5B
#define COMPLITEREMOTECONTROL_FUNCTION_REQUEST_DATA_LENGTH      4
#define COMPLITEREMOTECONTROL_FUNCTION_RESPONSE_DATA_LENGTH      4


#define illegal_function 1
#define illegal_data_address 2
#define illegal_data_value 3
#define slave_device_failure 4
#define acknowledge 5
#define slave_device_busy 6

class CustomFunctionMapping
	{
	    public :
	    unsigned char function;
	    unsigned char headerlength;
	    unsigned char datalength;

	    public :
	    CustomFunctionMapping(unsigned char function, unsigned char headerlength, unsigned char datalength);
	    ~CustomFunctionMapping();
	};
#endif